# -*- coding: utf-8 -*-
"""dinper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10YagAxTL76E8k9il7_MFfWICr03UMK9Z
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Data Wragling**

**Gathering Data**
"""

dinper_df = pd.read_csv("/content/Dinas Pertanian.csv")
print(dinper_df.shape)
print(dinper_df)

"""**Assessing Data**"""

# Menampilkan informasi pada dataset
dinper_df.info()

# Memeriksa missing value
dinper_df.isna().sum()

# Memeriksa duplikasi data
print("Jumlah duplikasi: ", dinper_df.duplicated().sum())

"""**Cleaning Data**"""

# Menghapus kolom yang tidak diperlukan
dinper_df = dinper_df.drop(columns=["Ket"])
print(dinper_df)

# Save data clean
dinper_df.to_csv('dinper_clean.csv', index=False)

"""# **Exploratory Data Analysis (EDA)**"""

# Melihat Jumlah Produksi Buah
# Baca file CSV
df = pd.read_csv("dinper_clean.csv")

# Filter baris yang mengandung "Jumlah Produksi Buah"
buah_df = df[df["Uraian"].str.contains("Jumlah Produksi Buah", case=False)].copy()

# Ekstrak nama kecamatan dari kolom 'Uraian'
buah_df["Kecamatan"] = buah_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung jumlah produksi per kecamatan
produksi_per_kecamatan = buah_df.groupby("Kecamatan")["2023"].sum().reset_index()

# Hitung total seluruh produksi buah
total_produksi = produksi_per_kecamatan["2023"].sum()

# Tampilkan tabel statistik deskriptif
statistik_tabel = produksi_per_kecamatan["2023"].describe().to_frame().rename(columns={"2023": "Statistik Produksi Buah"})

# Cetak hasil
print("\nJumlah Produksi Buah per Kecamatan:")
print(produksi_per_kecamatan)

print("\nTotal Seluruh Produksi Buah:", total_produksi, "Ton")

print("\nStatistik Deskriptif Produksi Buah per Kecamatan:")
print(statistik_tabel)

# Melihat Jumlah Produksi Sayuran
# Baca file CSV
df = pd.read_csv("dinper_clean.csv")

# Filter baris yang mengandung "Jumlah Produksi Sayuran"
sayur_df = df[df["Uraian"].str.contains("Jumlah Produksi Sayur", case=False)].copy()

# Ekstrak nama kecamatan dari kolom 'Uraian'
sayur_df["Kecamatan"] = sayur_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung jumlah produksi per kecamatan
produksi_per_kecamatan = sayur_df.groupby("Kecamatan")["2023"].sum().reset_index()

# Hitung total seluruh produksi Sayur
total_produksi = produksi_per_kecamatan["2023"].sum()

# Tampilkan tabel statistik deskriptif
statistik_tabel = produksi_per_kecamatan["2023"].describe().to_frame().rename(columns={"2023": "Statistik Produksi Sayur"})

# Cetak hasil
print("\nJumlah Produksi Sayur per Kecamatan:")
print(produksi_per_kecamatan)

print("\nTotal Seluruh Produksi Sayur:", total_produksi, "Ton")

print("\nStatistik Deskriptif Produksi Sayur per Kecamatan:")
print(statistik_tabel)

# Melihat Jumlah Produksi Obat Nabati
# Baca file CSV
df = pd.read_csv("dinper_clean.csv")

# Filter baris yang mengandung "Jumlah Produksi Obat"
obat_df = df[df["Uraian"].str.contains("Jumlah Produksi Obat Nabati", case=False)].copy()

# Ekstrak nama kecamatan dari kolom 'Uraian'
obat_df["Kecamatan"] = obat_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung jumlah produksi per kecamatan
produksi_per_kecamatan = obat_df.groupby("Kecamatan")["2023"].sum().reset_index()

# Hitung total seluruh produksi obat
total_produksi = produksi_per_kecamatan["2023"].sum()

# Tampilkan tabel statistik deskriptif
statistik_tabel = produksi_per_kecamatan["2023"].describe().to_frame().rename(columns={"2023": "Statistik Produksi Obat Nabati"})

# Cetak hasil
print("\nJumlah Produksi Obat Nabati per Kecamatan:")
print(produksi_per_kecamatan)

print("\nTotal Seluruh Produksi Obat Nabati:", total_produksi, "Ton")

print("\nStatistik Deskriptif Produksi Obat Nabati per Kecamatan:")
print(statistik_tabel)

# Melihat Jumlah Populasi Ternak Ayam
# Baca file CSV
df = pd.read_csv("dinper_clean.csv")

# Filter baris yang mengandung "Jumlah Populasi Ternak Ayam"
ayam_df = df[df["Uraian"].str.contains("Jumlah Populasi Ternak Ayam", case=False)].copy()

# Ekstrak nama kecamatan dari kolom 'Uraian'
ayam_df["Kecamatan"] = ayam_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung jumlah produksi per kecamatan
populasi_per_kecamatan = ayam_df.groupby("Kecamatan")["2023"].sum().reset_index()

# Hitung total seluruh populasi ayam
total_populasi = populasi_per_kecamatan["2023"].sum()

# Tampilkan tabel statistik deskriptif
statistik_tabel = populasi_per_kecamatan["2023"].describe().to_frame().rename(columns={"2023": "Statistik Populasi Ternak Ayam"})

# Cetak hasil
print("\nJumlah Populasi Ternak Ayam per Kecamatan:")
print(populasi_per_kecamatan)

print("\nTotal Seluruh Populasi Ternak Ayam:", total_populasi, "Ekor")

print("\nStatistik Deskriptif Populasi Ternak Ayam per Kecamatan:")
print(statistik_tabel)

# Melihat Jumlah Populasi Ternak Itik
# Baca file CSV
df = pd.read_csv("dinper_clean.csv")

# Filter baris yang mengandung "Jumlah Populasi Ternak Itik"
itik_df = df[df["Uraian"].str.contains("Jumlah Populasi Ternak Itik", case=False)].copy()

# Ekstrak nama kecamatan dari kolom 'Uraian'
itik_df["Kecamatan"] = itik_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung jumlah produksi per kecamatan
populasi_per_kecamatan = itik_df.groupby("Kecamatan")["2023"].sum().reset_index()

# Hitung total seluruh populasi itik
total_populasi = populasi_per_kecamatan["2023"].sum()

# Tampilkan tabel statistik deskriptif
statistik_tabel = populasi_per_kecamatan["2023"].describe().to_frame().rename(columns={"2023": "Statistik Populasi Ternak Itik"})

# Cetak hasil
print("\nJumlah Populasi Ternak Itik per Kecamatan:")
print(populasi_per_kecamatan)

print("\nTotal Seluruh Populasi Ternak Itik:", total_populasi, "Ekor")

print("\nStatistik Deskriptif Populasi Ternak Itik per Kecamatan:")
print(statistik_tabel)

"""# **Visualization & Explanatory Analysis**"""

# Luas Lahan
# Baca file CSV
df = pd.read_csv("dinper_clean.csv")

# Jenis lahan yang ingin divisualisasikan
list_lahan = [
    "Luas Lahan Sawah Beririgasi",
    "Luas Lahan Sawah Tadah Hujan",
    "Luas Lahan Kering Kebun",
    "Luas Lahan Kering Ladang"
]

# Filter data
lahan_df = df[df["Uraian"].isin(list_lahan)].copy()

# Ambil label dan nilai
labels = lahan_df["Uraian"]
sizes = lahan_df["2023"]

# Warna kustom pastel kontras
colors = ["#8ecae6", "#219ebc", "#ffb703", "#fb8500"]

# Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(
    sizes,
    labels=labels,
    colors=colors,
    autopct='%1.1f%%',
    startangle=140,
    textprops={'fontsize': 11, 'color': 'black'},
    wedgeprops={'edgecolor': 'white'}
)

# Lingkaran tengah agar jadi donut (opsional)
centre_circle = plt.Circle((0, 0), 0.60, fc='white')
fig = plt.gcf()
fig.gca().add_artist(centre_circle)

# Judul
plt.title("Distribusi Luas Lahan Pertanian per Jenis (2023)", fontsize=14, weight='bold')
plt.tight_layout()
plt.show()

# Jumlah Produksi Padi, Jagung, Buah, Sayuran, dan Obat Nabati
# Baca file CSV yang sudah dibersihkan
df = pd.read_csv("dinper_clean.csv")

# Definisikan daftar kata kunci kategori produksi
kategori_produksi = {
    "Jumlah Produksi Padi": "Padi",
    "Jumlah Produksi Jagung": "Jagung",
    "Jumlah Produksi Buah": "Buah",
    "Jumlah Produksi Sayur": "Sayuran",
    "Jumlah Produksi Obat Nabati": "Obat Nabati"
}

# Inisialisasi list untuk menyimpan total
hasil_total = []

# Hitung total untuk setiap kategori
for key, label in kategori_produksi.items():
    total = df[df["Uraian"].str.contains(key, case=False)]["2023"].sum()
    hasil_total.append((label, total))

# Ubah ke DataFrame
total_df = pd.DataFrame(hasil_total, columns=["Komoditas", "Jumlah Produksi"])

# Visualisasi
plt.figure(figsize=(10, 6))
bar = sns.barplot(data=total_df, x="Komoditas", y="Jumlah Produksi", palette="YlOrRd")

# Anotasi di atas batang
for p in bar.patches:
    bar.annotate(f'{p.get_height():,.0f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                 ha='center', va='bottom', fontsize=10, color='black')

# Styling
plt.title("Jumlah Produksi Komoditas Pertanian Tahun 2023", fontsize=14, weight='bold')
plt.ylabel("Jumlah Produksi (Ton)", fontsize=12)
plt.xlabel("Komoditas", fontsize=12)
plt.grid(axis='y', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# Ternak Ayam
# Baca data
df = pd.read_csv("dinper_clean.csv")

# Filter data untuk populasi ternak ayam
ayam_df = df[df["Uraian"].str.contains("Jumlah Populasi Ternak Ayam", case=False)].copy()

# Ekstrak nama kecamatan
ayam_df["Kecamatan"] = ayam_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung jumlah populasi per kecamatan
populasi_per_kecamatan = ayam_df.groupby("Kecamatan")["2023"].sum().reset_index()

# Visualisasi
plt.figure(figsize=(12, 6))
bar = sns.barplot(data=populasi_per_kecamatan, x="Kecamatan", y="2023", palette="coolwarm")

# Tambahkan anotasi pada tiap batang
for p in bar.patches:
    bar.annotate(f'{int(p.get_height()):,}', (p.get_x() + p.get_width() / 2., p.get_height()),
                 ha='center', va='bottom', fontsize=9, color='black')

# Styling
plt.title("Jumlah Populasi Ternak Ayam per Kecamatan (2023)", fontsize=14, weight='bold')
plt.xlabel("Kecamatan", fontsize=12)
plt.ylabel("Jumlah Populasi (Ekor)", fontsize=12)
plt.xticks(rotation=30)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# Baca data
df = pd.read_csv("dinper_clean.csv")

# Filter data untuk populasi ternak itik
itik_df = df[df["Uraian"].str.contains("Jumlah Populasi Ternak Itik", case=False)].copy()
itik_df["Kecamatan"] = itik_df["Uraian"].str.extract(r'Kecamatan\s+([\w\s]+)', expand=False).str.strip()

# Hitung total populasi itik per kecamatan
populasi_df = itik_df.groupby("Kecamatan")["2023"].sum().reset_index()
populasi_df = populasi_df.sort_values(by="2023", ascending=False)

# Plot Bubble Chart
plt.figure(figsize=(12, 8))
bubble = plt.scatter(
    x=populasi_df["Kecamatan"],
    y=populasi_df["2023"],
    s=populasi_df["2023"] / 5,  # Ukuran gelembung
    alpha=0.6,
    c=populasi_df["2023"],
    cmap="viridis",
    edgecolors='black',
    linewidths=1
)

# Label
for i, row in populasi_df.iterrows():
    plt.text(
        row["Kecamatan"],
        row["2023"] + 100,
        f'{int(row["2023"])}',
        ha='center',
        fontsize=9,
        fontweight='bold'
    )

plt.title("Jumlah Populasi Ternak Itik per Kecamatan (Bubble Chart)", fontsize=14, weight='bold')
plt.xlabel("Kecamatan", fontsize=12)
plt.ylabel("Jumlah Populasi (Ekor)", fontsize=12)
plt.xticks(rotation=25)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()