# -*- coding: utf-8 -*-
"""diskop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16kPt_rFQQkKG0hQOPmra4ULZEZ6QRceS
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""# **Data Wragling**

**Gathering Data**
"""

diskop_df = pd.read_csv("/content/Dinas Koperasi UMKM.csv")
print(diskop_df.shape)
print(diskop_df)

"""**Assessing Data**"""

# Menampilkan informasi pada dataset
diskop_df.info()

# Memeriksa missing value
diskop_df.isna().sum()

# Memeriksa duplikasi data
print("Jumlah duplikasi: ", diskop_df.duplicated().sum())

"""**Cleaning Data**"""

# Mengubah semua nama kolom menjadi string
diskop_df.columns = diskop_df.columns.map(str)
print(diskop_df)

# Save data clean
diskop_df.to_csv('diskop_clean.csv', index=False)

"""# **Exploratory Data Analysis (EDA)**"""

# Statistik deskriptif numerik
diskop_df.describe()

# Cek distribusi tiap kolom kategorikal
for col in diskop_df.select_dtypes(include='object').columns:
    print(f"\nDistribusi kategori pada kolom {col}:")
    print(diskop_df[col].value_counts())

# Melihat Jumlah UMKM Semua Bidang Tahun 2024
umkm_mask = diskop_df['Uraian'].str.contains("UMKM", case=False)
umkm_data = diskop_df[umkm_mask][['Uraian', '2024']].copy()
umkm_data['Bidang Usaha'] = umkm_data['Uraian'].str.replace('Jumlah UMKM Bidang ', '', regex=False)

# Tabel UMKM dan totalnya
umkm_table = umkm_data[['Bidang Usaha', '2024']].rename(columns={'2024': 'Jumlah'})

# Tambahkan total di baris akhir
total_row = pd.DataFrame({
    'Bidang Usaha': ['Total'],
    'Jumlah': [umkm_table['Jumlah'].sum()]
})

# Gabungkan tabel dengan total
umkm_table = pd.concat([umkm_table, total_row], ignore_index=True)

# Cetak tabel
print("Jumlah UMKM Kota Lubuk Linggau Tahun 2024:")
print(umkm_table)

# Melihat koperasi aktif simpan pinjam mandiri tahun 2022-2024
simpan_aktif = diskop_df[
    diskop_df['Uraian'].str.contains("koperasi aktif simpan pinjam", case=False) &
    diskop_df['Uraian'].str.contains("mandiri", case=False)
][['Uraian', '2022', '2023', '2024']]

# Ganti nama kolom untuk kejelasan
simpan_aktif = simpan_aktif.rename(columns={
    '2022': '2022',
    '2023': '2023',
    '2024': '2024'
})

# Tampilkan tabel
print("\nJumlah Koperasi Aktif Simpan Pinjam Mandiri:")
print(simpan_aktif)

# Melihat koperasi aktif serba usaha mandiri tahun 2022-2024
serba_aktif = diskop_df[
    diskop_df['Uraian'].str.contains("koperasi aktif serba usaha", case=False) &
    diskop_df['Uraian'].str.contains("mandiri", case=False)
][['Uraian', '2022', '2023', '2024']]

# Ganti nama kolom untuk kejelasan
serba_aktif = serba_aktif.rename(columns={
    '2022': '2022',
    '2023': '2023',
    '2024': '2024'
})

# Tampilkan tabel
print("\nJumlah Koperasi Aktif Simpan Serba Usaha:")
print(serba_aktif)

"""# **Visualization & Explanatory Analysis**"""

# Jumlah UMKM
# Siapkan data UMKM per bidang usaha tahun 2024
umkm_mask = diskop_df['Uraian'].str.contains("UMKM", case=False)
umkm_data = diskop_df[umkm_mask][['Uraian', '2024']].copy()
umkm_data['Bidang Usaha'] = umkm_data['Uraian'].str.replace('Jumlah UMKM Bidang ', '', regex=False)
umkm_data = umkm_data[['Bidang Usaha', '2024']].rename(columns={'2024': 'Jumlah UMKM (2024)'})
umkm_data = umkm_data.sort_values(by='Jumlah UMKM (2024)', ascending=True)

# Buat diagram horizontal barplot
plt.figure(figsize=(12, 7))
barplot = sns.barplot(
    data=umkm_data,
    x='Jumlah UMKM (2024)',
    y='Bidang Usaha',
    palette='coolwarm'
)

# Tambahkan anotasi nilai
for index, value in enumerate(umkm_data['Jumlah UMKM (2024)']):
    plt.text(value + 10, index, str(value), va='center', fontweight='bold', fontsize=9)

# Tampilan akhir
plt.title('Jumlah UMKM per Bidang Usaha Tahun 2024', fontsize=16, fontweight='bold')
plt.xlabel('Jumlah UMKM', fontsize=12)
plt.ylabel('Bidang Usaha', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

# Data jumlah koperasi aktif simpan pinjam mandiri
tahun = ['2022', '2023', '2024']
jumlah_koperasi = [57, 57, 57]

# Buat figure
plt.figure(figsize=(10, 6))
plt.plot(tahun, jumlah_koperasi, marker='o', linestyle='-', linewidth=3, color='teal')

# Anotasi nilai tiap titik
for i, value in enumerate(jumlah_koperasi):
    plt.text(tahun[i], value + 1, str(value), ha='center', fontsize=10, fontweight='bold')

# Tambahan efek visual
plt.fill_between(tahun, jumlah_koperasi, color='teal', alpha=0.1)
plt.title("Jumlah Koperasi Aktif Simpan Pinjam Mandiri (2022–2024)", fontsize=16, fontweight='bold')
plt.xlabel("Tahun", fontsize=12)
plt.ylabel("Jumlah Koperasi", fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.ylim(0, max(jumlah_koperasi) + 10)
plt.tight_layout()
plt.show()

# Data koperasi aktif serba usaha mandiri tahun 2022-2024
tahun = ['2022', '2023', '2024']
jumlah_koperasi = [60, 61, 61]

# Warna gradasi
colors = ['#A1C9F4', '#76B7B2', '#59A14F']

# Buat diagram horizontal bar
plt.figure(figsize=(10, 6))
bars = plt.barh(tahun, jumlah_koperasi, color=colors)

# Anotasi angka di setiap bar
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.3, bar.get_y() + bar.get_height()/2,
             str(int(width)), va='center', fontweight='bold')

# Judul dan dekorasi
plt.title("Jumlah Koperasi Aktif Serba Usaha Mandiri (2022–2024)",
          fontsize=16, fontweight='bold')
plt.xlabel("Jumlah Koperasi")
plt.ylabel("Tahun")
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()